/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication3;

import java.awt.Component;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;


/**
 *
 * @author Taylor
 */
public class GUI extends javax.swing.JFrame {
    int highestPower;
    /**
     * Creates new form NewJFrame
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        solveButton = new javax.swing.JButton();
        highestPowerField = new javax.swing.JTextField();
        highestPowerLabel = new javax.swing.JLabel();
        coefficientPrompt = new javax.swing.JLabel();
        highestPowerErrorLabel = new javax.swing.JLabel();
        coefficientScrollPanel = new javax.swing.JScrollPane();
        coefficientPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        solveButton.setVisible(false);
        solveButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        solveButton.setText("Solve");
        solveButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                solveButtonMouseClicked(evt);
            }
        });
        getContentPane().add(solveButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 205, -1, -1));

        highestPowerField.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        highestPowerField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                highestPowerActionPerformed(evt);
            }
        });
        highestPowerField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                highestPowerKeyTyped(evt);
            }
        });
        getContentPane().add(highestPowerField, new org.netbeans.lib.awtextra.AbsoluteConstraints(531, 0, 100, 40));

        highestPowerLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        highestPowerLabel.setText("Please enter the highest power of the polynomial:");
        getContentPane().add(highestPowerLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 35));

        coefficientPrompt.setVisible(false);
        coefficientPrompt.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        coefficientPrompt.setText("Please enter the coefficients for each partner of x in the polynomial:");
        getContentPane().add(coefficientPrompt, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 53, 803, 40));

        highestPowerErrorLabel.setVisible(false);
        highestPowerErrorLabel.setForeground(new java.awt.Color(204, 0, 0));
        highestPowerErrorLabel.setText("Invalid input. Please try again.");
        getContentPane().add(highestPowerErrorLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(631, 14, -1, -1));

        coefficientScrollPanel.setVisible(false);
        coefficientScrollPanel.setRequestFocusEnabled(false);

        coefficientPanel.setVisible(false);
        coefficientPanel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        coefficientPanel.setMaximumSize(new java.awt.Dimension(730, 100));
        coefficientPanel.setMinimumSize(new java.awt.Dimension(730, 100));
        coefficientPanel.setName(""); // NOI18N

        javax.swing.GroupLayout coefficientPanelLayout = new javax.swing.GroupLayout(coefficientPanel);
        coefficientPanel.setLayout(coefficientPanelLayout);
        coefficientPanelLayout.setHorizontalGroup(
            coefficientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        coefficientPanelLayout.setVerticalGroup(
            coefficientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        coefficientScrollPanel.setViewportView(coefficientPanel);

        getContentPane().add(coefficientScrollPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 98, 730, 100));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void highestPowerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_highestPowerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_highestPowerActionPerformed
    public static String superscript(String str) {
    str = str.replaceAll("0", "⁰");
    str = str.replaceAll("1", "¹");
    str = str.replaceAll("2", "²");
    str = str.replaceAll("3", "³");
    str = str.replaceAll("4", "⁴");
    str = str.replaceAll("5", "⁵");
    str = str.replaceAll("6", "⁶");
    str = str.replaceAll("7", "⁷");
    str = str.replaceAll("8", "⁸");
    str = str.replaceAll("9", "⁹");         
    return str;
    }

    private void highestPowerKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_highestPowerKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        try{
            if(c==KeyEvent.VK_ENTER && (Integer.valueOf(highestPowerField.getText()) > 0)){
                coefficientPanel.revalidate();
                coefficientPanel.removeAll();
                highestPowerErrorLabel.setVisible(false);
                coefficientPrompt.setVisible(true);
                coefficientPanel.setVisible(true);
                coefficientScrollPanel.setVisible(true);
                solveButton.setVisible(true);
                highestPower = Integer.valueOf(highestPowerField.getText());
                coefficientPanel.setLayout(new FlowLayout());
                while(highestPower != 0){
                    String as1 = "x^"+highestPower;
                    JLabel label = new JLabel(as1);
                    label.setFont(new Font("Tahoma", Font.PLAIN, 20));
                    field = new JTextField();
                    field.setFont(new Font("Tahoma", Font.PLAIN, 20));
                    field.setPreferredSize(new Dimension(60, 40));
                    String as2 = "+";
                    String as3 = "-";
                    final JButton button = new JButton(as2);
                    button.addActionListener((ActionEvent e) -> {
                        if(button.getText() == null || button.getText().equals(as2)){
                            button.setText(as3);
                        }
                        else{
                            button.setText(as2);
                        }
                    });
                    button.setPreferredSize(new Dimension(60, 40));
                    button.setFont(new Font("Tahoma", Font.PLAIN, 20));                    
                    coefficientPanel.add(button);
                    coefficientPanel.add(field);
                    coefficientPanel.add(label);

                    allFields.add(field);
                    allSigns.add(button);
                    highestPower -= 1;
                    if(highestPower == 0){
                         final JButton button2 = new JButton(as2);
                         button2.addActionListener((ActionEvent e) -> {
                        if(button2.getText() == null || button2.getText().equals(as2)){
                            button2.setText(as3);
                        }
                        else{
                            button2.setText(as2);
                        }
                    });
                         button2.setPreferredSize(new Dimension(60, 40));
                         button2.setFont(new Font("Tahoma", Font.PLAIN, 20));
                         coefficientPanel.add(button2);
                         field = new JTextField();
                         field.setFont(new Font("Tahoma", Font.PLAIN, 20));
                         field.setPreferredSize(new Dimension(60, 40));
                         coefficientPanel.add(field);
                         allFields.add(field);
                         allSigns.add(button2);
                    }
                }
                
            }
            if(!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE) || (c==KeyEvent.VK_DELETE))){
                highestPowerErrorLabel.setVisible(false);
                evt.consume();
            }
        }
        catch(NumberFormatException e){
                highestPowerErrorLabel.setVisible(true);
        }
    }//GEN-LAST:event_highestPowerKeyTyped

    private void solveButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_solveButtonMouseClicked
        // TODO add your handling code here:
        revalidate();
        for(int i=0; i < allFields.size(); i++){
            coefficient.add(Integer.valueOf(allFields.get(i).getText()));
            System.out.println(coefficient.get(i));
        }
        for(int i=0; i < allSigns.size(); i++){
            sign.add(allSigns.get(i).getText());
            System.out.println(sign.get(i));
        }
        Calculations solve = new Calculations(coefficient, sign);
        textDatabase.add(coefficient);
        buttonDatabase.add(sign);
        for(int i=0; i < allFields.size(); i++){
            allFields.remove(i);
            coefficient.remove(i);
        }
        for(int i=0; i < allSigns.size(); i++){
            allSigns.remove(i);
            sign.remove(i);
        }
        ResultGUI solved = new ResultGUI();
        solved.setVisible(true);
    }//GEN-LAST:event_solveButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new GUI().setVisible(true);
        });
    }
    private final List<List<Integer>> textDatabase = new ArrayList<List<Integer>>();
    private final List<List<String>> buttonDatabase = new ArrayList<List<String>>();
    private final List<JTextField> allFields = new ArrayList<JTextField>();
    private final List<JButton> allSigns = new ArrayList<JButton>();
    private JTextField field;
    private List<Integer> coefficient = new ArrayList<Integer>();
    private List<String> sign = new ArrayList<String>();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel coefficientPanel;
    private javax.swing.JLabel coefficientPrompt;
    private javax.swing.JScrollPane coefficientScrollPanel;
    private javax.swing.JLabel highestPowerErrorLabel;
    private javax.swing.JTextField highestPowerField;
    private javax.swing.JLabel highestPowerLabel;
    private javax.swing.JButton solveButton;
    // End of variables declaration//GEN-END:variables
}
