package Main;

import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;


/**
 *
 * @author Taylor
 */
@SuppressWarnings("serial")
public class Window extends javax.swing.JFrame {
    int highestPower;
    /**
     * Creates new form NewJFrame
     */
    public Window() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        solveButton = new javax.swing.JButton();
        highestPowerField = new javax.swing.JTextField();
        highestPowerLabel = new javax.swing.JLabel();
        coefficientPrompt = new javax.swing.JLabel();
        highestPowerErrorLabel = new javax.swing.JLabel();
        coefficientScrollPanel = new javax.swing.JScrollPane();
        coefficientPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(900, 400));
        setResizable(false);

        solveButton.setVisible(false);
        solveButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        solveButton.setText("Solve");

        highestPowerField.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        highestPowerField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                highestPowerActionPerformed(evt);
            }
        });
        highestPowerField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                highestPowerKeyTyped(evt);
            }
        });

        highestPowerLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        highestPowerLabel.setText("Please enter the highest power of the polynomial:");

        coefficientPrompt.setVisible(false);
        coefficientPrompt.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        coefficientPrompt.setText("Please enter the coefficients for each partner of x in the polynomial:");

        highestPowerErrorLabel.setVisible(false);
        highestPowerErrorLabel.setForeground(new java.awt.Color(204, 0, 0));
        highestPowerErrorLabel.setText("Invalid input. Please try again.");

        coefficientScrollPanel.setVisible(false);
        coefficientScrollPanel.setRequestFocusEnabled(false);

        coefficientPanel.setVisible(false);
        coefficientPanel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        coefficientPanel.setMaximumSize(new java.awt.Dimension(730, 100));
        coefficientPanel.setMinimumSize(new java.awt.Dimension(730, 100));
        coefficientPanel.setName(""); // NOI18N

        javax.swing.GroupLayout coefficientPanelLayout = new javax.swing.GroupLayout(coefficientPanel);
        coefficientPanel.setLayout(coefficientPanelLayout);
        coefficientPanelLayout.setHorizontalGroup(
            coefficientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        coefficientPanelLayout.setVerticalGroup(
            coefficientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        coefficientScrollPanel.setViewportView(coefficientPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(solveButton)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(highestPowerLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(highestPowerField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(highestPowerErrorLabel))
                    .addComponent(coefficientPrompt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(coefficientScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 730, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(highestPowerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(highestPowerField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(highestPowerErrorLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(coefficientPrompt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(coefficientScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(solveButton)
                .addGap(0, 158, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void highestPowerActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            


    private void highestPowerKeyTyped(java.awt.event.KeyEvent evt) {                                      
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        try{
            if(c==KeyEvent.VK_ENTER && (Integer.valueOf(highestPowerField.getText()) > 0)){
                coefficientPanel.revalidate();
                coefficientPanel.removeAll();
                highestPowerErrorLabel.setVisible(false);
                coefficientPrompt.setVisible(true);
                coefficientPanel.setVisible(true);
                coefficientScrollPanel.setVisible(true);
                solveButton.setVisible(true);
                highestPower = Integer.valueOf(highestPowerField.getText());
                coefficientPanel.setLayout(new FlowLayout());
                while(highestPower != 0){
                    String as1 = "x^"+highestPower;
                    JLabel label = new JLabel(as1);
                    label.setFont(new Font("Tahoma", Font.PLAIN, 20));
                    JTextField field = new JTextField();
                    field.setFont(new Font("Tahoma", Font.PLAIN, 20));
                    field.setPreferredSize(new Dimension(60, 40));
                    String as2 = "+";
                    String as3 = "-";
                    JButton button = new JButton(as2);
                    button.addActionListener((ActionEvent e) -> {
                        if(button.getText() == null ? null == as2 : button.getText().equals(as2)){
                            button.setText(as3);
                        }
                        else{
                            button.setText(as2);
                        }
                    });
                    button.setPreferredSize(new Dimension(60, 40));
                    button.setFont(new Font("Tahoma", Font.PLAIN, 20));
                    
                    coefficientPanel.add(field);
                    coefficientPanel.add(label);
                    coefficientPanel.add(button);
                    highestPower -= 1;
                    if(highestPower == 0){
                         coefficientPanel.add(field);
                    }
                }
                
            }
            if(!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE) || (c==KeyEvent.VK_DELETE))){
                highestPowerErrorLabel.setVisible(false);
                evt.consume();
            }
        }
        catch(NumberFormatException e){
                highestPowerErrorLabel.setVisible(true);
        }
    }                                     

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Window().setVisible(true);
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JPanel coefficientPanel;
    private javax.swing.JLabel coefficientPrompt;
    private javax.swing.JScrollPane coefficientScrollPanel;
    private javax.swing.JLabel highestPowerErrorLabel;
    private javax.swing.JTextField highestPowerField;
    private javax.swing.JLabel highestPowerLabel;
    private javax.swing.JButton solveButton;
    // End of variables declaration                   
}